services:
  hda-eco:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - db:/app/data
      - up:/app/uploads
      - ./DATA0001.TXT:/app/DATA0001.TXT
      - ./DATAOUT.TXT:/app/DATAOUT.TXT
    restart: unless-stopped

volumes:
  db:
  up:
